fix pre commit to hook to only check if key is in staged files (#466)

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,12 +1,15 @@
 #!/bin/sh
 
-key_matches=$(grep -Eo "prj_...._pk_.{40}" Example/Example/AppDelegate.swift)
-zerokey="prj_...._pk_0{40}"
+if git diff --cached --name-only | grep -q "Example/Example/AppDelegate.swift"; then
+    key_matches=$(grep -Eo "prj_...._pk_.{40}" Example/Example/AppDelegate.swift)
+    zerokey="prj_...._pk_0{40}"
 
-for key in $key_matches;
-do
-    if [[ ! $key =~ $zerokey ]]; then
-        echo "Aborted\nDetected Radar API key: $key"
-        exit 1
-    fi
-done
+    for key in $key_matches;
+    do
+        if [[ ! $key =~ $zerokey ]]; then
+            echo "Aborted"
+            echo "Detected Radar API key: $key"
+            exit 1
+        fi
+    done
+fi
